---
title: '[firebase] cloud functionsが実行出来ない blocked by CORS policy'
tags:
  - Firebase
  - cloudfunctions
private: false
updated_at: '2022-09-28T21:14:33+09:00'
id: 0e4971d44205240242c5
organization_url_name: null
slide: false
ignorePublish: false
---
# 背景
Firebaseで動かしてたサービスがcloud functionsへアクセスが出来なくなる問題に遭遇。
急にアクセス出来ないかつ心当たりなさすぎたのでハマった。一旦治ったのでまとめる

1. cloud functions側でonCallのエンドポイントを作成。
```functions.js
exports.func = functions.https.onCall((data) => {
    // ...
});
```
2. クライアントからfirebase.onRequestで呼び出す。
```client.js
functions.httpsCallable("func");
```

# エラー内容
functions側のlogは出ない。そもそもapiを叩けていない状況

consoleを見るとなんか出てる
cors、、、君だったのか、いやいやでもonCallはcors出ないんじゃなかったの？（詳しくは加筆）
```js
blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

# 解決法
こちらの記事の通り。
https://qiita.com/tekunikaruza_jp/items/c068506ca0d6d648cc50

簡単にまとめると権限のエラー
1. gcpで[cloud functions](https://cloud.google.com/functions?hl=ja) 該当の関数にアクセス
1. 権限 > 追加でallusersにすれば良い。
![スクリーンショット 2022-09-28 21.08.32.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/787586/1d0c8bd4-4d13-caf7-76c5-b052185d64d6.png)

元々allUsersを許容していた関数を作り直した際に権限がリセットされたことが原因？
とりあえず解決するのだが、allUsersってそもそも良いんだっけ？
もうちょっと調査する必要がありそう。
続

